# Docker Compose Override for Testing Traefik without Application Images
# Use this file to test Traefik configuration when application images are not available
#
# Usage: docker compose -f docker-compose.yml -f docker-compose.test.yml up -d

services:
  # Replace webapp with a simple nginx container for testing
  webapp:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME:-digitalbot}-app-test
    volumes:
      - ./test-content:/usr/share/nginx/html:ro
    environment:
      - NGINX_PORT=8080
    command: sh -c "echo '<h1>Test Web App - Traefik Working!</h1><p>If you see this, Traefik is routing correctly.</p>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Replace client-app with a simple nginx container
  client-app:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME:-digitalbot}-client-app-test
    command: sh -c "echo '<h1>Test Client App - Traefik Working!</h1><p>Client routing is functioning correctly.</p>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Disable processor and order-worker for testing
  processor:
    deploy:
      replicas: 0

  order-worker:
    deploy:
      replicas: 0