http:
  middlewares:
    default-security:
      headers:
        stsSeconds: 15552000            # 180 days
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: no-referrer-when-downgrade
        # Hide backend server header
        customResponseHeaders:
          Server: ""

# TLS hardening options
# You can reference this as tls.options.default in routers if needed.
tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: false
      preferServerCipherSuites: true
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384

