http:
  middlewares:
    default-security:
      headers:
        stsSeconds: 31536000            # 1 year HSTS
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: strict-origin-when-cross-origin
        permissionsPolicy: geolocation=(), microphone=(), camera=()
        # Hide backend server header
        customResponseHeaders:
          Server: ""
          X-Powered-By: ""

    # Rate limiting for public endpoints
    rate-limit:
      rateLimit:
        average: 100
        period: 1m
        burst: 200

    # Basic auth for admin interfaces (optional)
    admin-auth:
      basicAuth:
        removeHeader: true
        users:
          - "admin:$apr1$4J4OgWyf$gOlvvNwFAK3IPSkW7eK7h."

    # Dashboard specific auth
    dashboard-auth:
      basicAuth:
        removeHeader: true
        users:
          - "ali:$apr1$0M3AZz6/$LExNx/0/r7N8pKuELfqNS1"

# Enhanced TLS configuration compatible with Cloudflare
tls:
  options:
    default:
      minVersion: VersionTLS12
      maxVersion: VersionTLS13
      sniStrict: false
      cipherSuites:
        # TLS 1.3 ciphers (preferred)
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_AES_128_GCM_SHA256
        # TLS 1.2 ciphers (Cloudflare compatibility)
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
        - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
      curvePreferences:
        - X25519
        - secp384r1
        - secp256r1
    
    # Alternative TLS option for Cloudflare compatibility
    cloudflare:
      minVersion: VersionTLS12
      maxVersion: VersionTLS13
      sniStrict: false

