# TLS configuration optimized for Cloudflare compatibility and speed
# This file addresses SSL validation issues (Error 526)

tls:
  options:
    # Default TLS configuration with Cloudflare compatibility
    default:
      minVersion: VersionTLS12
      maxVersion: VersionTLS13
      sniStrict: false
      # Optimized cipher suites for Cloudflare compatibility and performance
      cipherSuites:
        # TLS 1.3 (modern, fastest)
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_AES_128_GCM_SHA256
        # TLS 1.2 (for compatibility, most common with Cloudflare)
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      curvePreferences:
        - X25519
        - secp384r1
        - secp256r1
      # Optimized for faster handshakes
      alpnProtocols:
        - h2
        - http/1.1

# HTTP configuration for proper certificate validation and Cloudflare compatibility
http:
  middlewares:
    # Optimized security headers for Cloudflare
    cloudflare-security:
      headers:
        # HSTS optimized for Cloudflare
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        # Content security
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        # Hide server info for security
        customResponseHeaders:
          Server: ""
          X-Powered-By: ""
          X-Frame-Options: "DENY"
          X-Content-Type-Options: "nosniff"
          # Cloudflare-friendly headers
          CF-IPCountry: ""
          CF-Ray: ""